version: "3.8"

services:
  chat:
    image: orangery/stack-chat-api:latest
    container_name: ${APP_NAME:-stack-chat}-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - stack-network

networks:
  stack-network:
    external: true
