#!/usr/bin/env node

/**
 * Pre-deployment check script for Stack Chat API
 * Run this before deploying to Render.com to ensure everything is configured correctly
 */

const fs = require('fs');
const path = require('path');

console.log('🚀 Stack Chat API - Pre-deployment Check\n');

// Check if required files exist
const requiredFiles = [
  'package.json',
  'render.yaml',
  'src/main.ts',
  'src/app.module.ts',
  'src/config/database.module.ts'
];

console.log('📁 Checking required files...');
let allFilesExist = true;

requiredFiles.forEach(file => {
  if (fs.existsSync(file)) {
    console.log(`✅ ${file}`);
  } else {
    console.log(`❌ ${file} - MISSING!`);
    allFilesExist = false;
  }
});

if (!allFilesExist) {
  console.log('\n❌ Some required files are missing. Please ensure all files exist before deployment.');
  process.exit(1);
}

// Check package.json scripts
console.log('\n📋 Checking package.json scripts...');
const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));

const requiredScripts = ['build', 'start:prod'];
let allScriptsExist = true;

requiredScripts.forEach(script => {
  if (packageJson.scripts && packageJson.scripts[script]) {
    console.log(`✅ ${script}: ${packageJson.scripts[script]}`);
  } else {
    console.log(`❌ ${script} - MISSING!`);
    allScriptsExist = false;
  }
});

if (!allScriptsExist) {
  console.log('\n❌ Some required scripts are missing in package.json');
  process.exit(1);
}

// Check if render.yaml is properly configured
console.log('\n🔧 Checking render.yaml configuration...');
const renderYaml = fs.readFileSync('render.yaml', 'utf8');

const renderChecks = [
  { check: 'type: web', description: 'Web service configuration' },
  { check: 'env: node', description: 'Node.js environment' },
  { check: 'buildCommand:', description: 'Build command' },
  { check: 'startCommand:', description: 'Start command' },
  { check: 'healthCheckPath:', description: 'Health check path' },
  { check: 'MONGODB_URI', description: 'MongoDB configuration' }
];

renderChecks.forEach(({ check, description }) => {
  if (renderYaml.includes(check)) {
    console.log(`✅ ${description}`);
  } else {
    console.log(`❌ ${description} - MISSING!`);
  }
});

// Environment variables checklist
console.log('\n🔑 Environment Variables Checklist:');
console.log('Please ensure the following environment variables are set in Render dashboard:');

const envVars = [
  // Auto-configured variables
  { name: 'NODE_ENV', required: true, description: 'Auto-set to "production"' },
  { name: 'APP_PORT', required: true, description: 'Auto-set to "10000"' },
  
  // Manually set variables
  { name: 'APP_URL', required: true, description: 'Set to your Render app URL' },
  { name: 'MONGODB_URI', required: true, description: 'Your MongoDB Atlas connection string' },
  { name: 'MAIL_USER', required: true, description: 'Gmail address for sending emails' },
  { name: 'MAIL_PASS', required: true, description: 'Gmail app password (not regular password)' },
  { name: 'GOOGLE_CLIENT_ID', required: true, description: 'Google OAuth client ID' },
  { name: 'GOOGLE_CLIENT_SECRET', required: true, description: 'Google OAuth client secret' },
  { name: 'GOOGLE_CALLBACK_URL', required: true, description: 'Google OAuth callback URL' },
  
  // Auto-generated variables
  { name: 'JWT_ACCESS_SECRETKEY', required: true, description: 'Auto-generated by Render' },
  { name: 'JWT_REFRESH_SECRETKEY', required: true, description: 'Auto-generated by Render' },
  { name: 'SESSION_SECRET', required: true, description: 'Auto-generated by Render' },
  
  // Optional configuration
  { name: 'ENABLE_SWAGGER', required: false, description: 'Enable API documentation' },
  { name: 'KEEP_ALIVE_ENABLED', required: false, description: 'Enable keep-alive service' },
  { name: 'CORS_ORIGIN', required: false, description: 'CORS origin configuration' },
  { name: 'TZ', required: false, description: 'Timezone setting' }
];

envVars.forEach(({ name, required, description }) => {
  const status = required ? '🔴 REQUIRED' : '🟡 OPTIONAL';
  console.log(`  ${status} ${name}: ${description}`);
});

console.log('\n📖 Deployment Instructions:');
console.log('1. Push your code to GitHub');
console.log('2. Go to render.com and create a new Blueprint');
console.log('3. Connect your GitHub repository');
console.log('4. Render will automatically detect render.yaml');
console.log('5. Set the required environment variables in Render dashboard');
console.log('6. Deploy and monitor the logs');

console.log('\n🔗 Useful URLs after deployment:');
console.log('- API Base: https://your-app-name.onrender.com/api');
console.log('- Health Check: https://your-app-name.onrender.com/api/keep-alive/status');
console.log('- API Docs: https://your-app-name.onrender.com/api/docs');

console.log('\n✅ Pre-deployment check completed successfully!');
console.log('Your application is ready to be deployed to Render.com');
